language: node_js
node_js: stable
before_script:
- gem install percy-cli
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && npm run perceptual-diff'
env:
  global:
    secure: JVWwRf2/1kddfQBmjrStRg3HoTCjibl89rCRmrYxAvGmQ4Wp5ngqh3n0LLLci7zT7SmeOXdufTEABtamOw4HMGshAiCuk/vZtZ40Sh7qQdl6xs1uu353PuOI0qmmmLFzWvWvP+drooBumWrzD0tHey3yxSnZsPPNRXOUZeeSe7U51M7C38tLwHxZelhz8DMk81TD18Du/XsfVB2gBAcRT2KmJeeveduC8R75helJBFGOVkoCdzmZDLIaVSJXWhth+iBuAqZPabhNx97RXQRLsg3aW6GnnZTHyPUJes02OqnrICGiSScCSKhht6sCX0GGo6t50vBXvx54zbsDelUEgv4ZwOm2t69dTPtVbwq7//RfVm0oP6KlmKFJSgabfPo1FFCGKmzWyCNP5YAdK3Sgf9To3D5jYpu1H4xblJQ25fyN46Qvi2sVaowpBlrkyIOb78fadW2aRO5I6yRNZGkYCjpRnFMfyxCyHobEtlfbPSjiWMc/SO0/sd5AAr8PeM9jwPbZWQZpTZg18GU2cWz3NSQQQNRow8QYZL00UVn/GiT7z1UndteytqLPeIqLu9FZMaxAxPIAjXsX168rOP99tGxpo9HKilRm2pP2UAlflNaZV+twJEdHduxzwW6e3VIroFgwMvOHW8AwOxofZfKVve94DEhrvfaDMzqIapne3Jc=
